name: Build

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  windows-build:
    runs-on: windows-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build project
        run: cargo build --verbose
      - name: Package release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          $VERSION = $env:GITHUB_REF -replace 'refs/tags/', ''
          $ARCHIVE_NAME = "3d-renderer-rust-$VERSION-win64"
          cargo build --release --verbose
          mkdir "$ARCHIVE_NAME"
          Copy-Item LICENSE -Destination "$ARCHIVE_NAME"
          Copy-Item README.md -Destination "$ARCHIVE_NAME"
          Copy-Item assets -Destination "$ARCHIVE_NAME" -Recurse
          Copy-Item doc -Destination "$ARCHIVE_NAME" -Recurse
          Copy-Item target/release/3d-renderer-rust.exe -Destination "$ARCHIVE_NAME"
          Compress-Archive -Path "$ARCHIVE_NAME" -DestinationPath "$ARCHIVE_NAME.zip"
      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            3d-renderer-rust-*.zip

  linux-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build project
        run: cargo build --verbose
      - name: Package release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=$(echo ${{ github.ref }} | sed 's/refs\/tags\///')
          ARCHIVE_NAME=3d-renderer-rust-$VERSION-linux-x86_64
          cargo build --release --verbose
          mkdir "$ARCHIVE_NAME"
          cp -R assets doc LICENSE target/release/3d-renderer-rust README.md "$ARCHIVE_NAME/"
          tar -czvf "$ARCHIVE_NAME.tar.gz" "$ARCHIVE_NAME"
      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            3d-renderer-rust-*.tar.gz

  web-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install Node.js dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
